### ISSUE TITLE
Decide whether Python2 support should be abandoned

### ISSUE THREAD

**Issue by mb1a15** [joommf/joommf#10]
Because of the inconsistencies between Python2 and Python3, the code gets more complicated and also testing becomes more difficult. This is mainly a problem with continuous integration and testing in multiple different Docker containers.

**Comment by mb1a15** [comment]
After a discussion, it was decided to abandon Python2 support because this is going to save a lot of time during development. On the other hand, if somebody requires Python2 version of the code, it should not be too difficult to do relevant changes of the code in the end.

**Comment by fangohr** [comment]
Having a code based purely on Python 3 will make the code (somewhat) easier to read, thus allowing more people to contribute. Experience has shown that it is important to keep codes accessible to the user base to attract future developers [1]. 
Furthermore, our use base splits into two groups: those that haven't used Python at all yet (as OOMMF doesn't need Python), and they might as well start with Python 3. Those that happen to know Python from other projects or their own initiative are generally so advanced that they can switch from Python 2 to 3, if they haven't done so already, or manage parallel environments. 

In the long run, Python 3 is the tool to use; Python 2 will not be supported indefinitely - neither by the Python Software Foundation nor by third party libraries we depend on. 

[1] http://doi.acm.org/10.1145/2897676.2897677
