### ISSUE TITLE
UML class diagram for `micromagneticmodel` package

### ISSUE THREAD

**Issue by mb1a15** [joommf/joommf#16]
After all related issues are solved, a UML diagram should be created.

**Comment by mb1a15** [comment]
Commands are:
`
apt-get install pylint graphviz
pyreverse -o pdf packagename
`

**Comment by mb1a15** [comment]
![micromagneticmodel_uml](https://cloud.githubusercontent.com/assets/12461206/17212138/739c1b32-54c5-11e6-8312-5037726accad.jpg)

**Comment by fangohr** [comment]
If you haven't done so, let's add a script or makefile target to the repo that runs this command.

Sent from smartphone

On 28 Jul 2016, at 13:08, Marijan Beg <notifications@github.com<mailto:notifications@github.com>> wrote:


Commands are:

apt-get install pylint graphviz
pyreverse -o pdf packagename

�

**Comment by mb1a15** [comment]
Not an issue any more.
