### ISSUE TITLE
All objects should have representation methods for Jupyter notebooks

### ISSUE THREAD

**Issue by mb1a15** [joommf/joommf#19]
`Field` class is missing Jupyter notebook representation method.

**Comment by mb1a15** [comment]
What should be the representation method for `system` object?

**Comment by fangohr** [comment]
Let's start with a tuple of the components that makes up the system. Each part of the tuple can use their own textual representation.

**Comment by mb1a15** [comment]
All objects now have representations, except the Field. This is issue no.10 in discretisedfield repository. Therefore, this issue is now closed.
