### ISSUE TITLE
Testing packages as dependencies

### ISSUE THREAD

**Issue by mb1a15** [joommf/joommf#28]
Should testing packages (pytest, codecov, coverage, nbval) be installed when our package is installed via `pip`?

**Comment by fangohr** [comment]
Hm, difficult question. 

On the one hand, I'd like to keep the packages as lean as possible. That would suggest not to include the dependencies you list, which are mostly for the benefit of developers.

On the other hand, I quite like when tests are included with a package and distributed with it. For example, scipy allows to run 
    import scipy
    scipy.test()
and this will run its testing suite. For this to work, we would need to have `py.test` on the system (and  also `nbval`). 

How about we distribute without tests for now, and have some more brainstorming in person (and invite views from others). I think may well be inclined to argue that users should be able to run the tests eventually.

**Comment by mb1a15** [comment]
Ok, I checked the `numpy` repository (https://github.com/numpy/numpy) README, where they say:

After installation, tests can be run (if nose is installed) with:
```
python -c 'import numpy; numpy.test()'
```

They explicitly say "if nose is installed". So, maybe if we include tests in the package, but we do not put `pytest` and `nbval` in the list of dependencies.

**Comment by fangohr** [comment]
Good idea. We could actually check wether the right packages are installed then the `test()` function is called, and if not display a message that explains which packages are required.

**Comment by mb1a15** [comment]
The test function is now added to all four packages. If `pytest` is installed, `python3 -c "import oommfc; oommfc.test()"` runs the unit tests.

**Comment by mb1a15** [comment]
Should `oommfc.test()` also run notebook tests?

**Comment by mb1a15** [comment]
Output of `oommfc.test()` should be more informative. `-v` should be added to the `pytest.main()` list of arguments.

**Comment by mb1a15** [comment]
`package.test()` should not run notebook tests because the user will need nbval and jupyter.

**Comment by mb1a15** [comment]
Changed on master on all packages.
