### ISSUE TITLE
All abstract classes in `micromagneticmodel` should have `__repr__` method.

### ISSUE THREAD

**Issue by mb1a15** [joommf/joommf#3]
For instance, `__repr__` method in Exchange class should return `Exchange(A=8.78e-12)`. Similarly, `Hamiltonian` and `Dynamics` classes are expected to return "a sum" of individual term representations. For example, `Exchange(A=8.78e12) + Demag() + Zeeman(H=(0, 0, 1e6))`.

**Comment by mb1a15** [comment]
It is not clear what should be the representation string for an empty Hamiltonian or Dynamics. Should it be an empty string ('') or zero ('0').

**Comment by mb1a15** [comment]
An empty Hamiltonian and Dynamics should return '0' as a representation string.

**Comment by mb1a15** [comment]
`Mesh` and `Field` are still missing `__repr__` methods.

**Comment by mb1a15** [comment]
A question is what should be the `__repr__` method for the system object.

**Comment by mb1a15** [comment]
What should be `__repr__` method for `system` object?

**Comment by fangohr** [comment]
Let's start with just calling `__str__` when `__repr__` is called. If we could find a representation that fully re-creates the object, this would be great, but I think we can't, can we?

**Comment by mb1a15** [comment]
This issue is now solved on master.
