### ISSUE TITLE
Default matplotlib backend

### ISSUE THREAD

**Issue by mb1a15** [joommf/joommf#30]
At the moment, we have
```
import matplotlib
matplotlib.use("nbagg")
```
in `__init__.py` file(s) across packages. This works fine only when the code is run from the command line `python3 filename.py` or inside Jupyter notebook.

However, inside `python3` or `ipython` kernel, we cannot import the package because `nbagg` is not supported.

Do we need a default backend? If yes, what it should be?

(If we do not have a default one, we get warnings when packages are imported across different platforms, issue001 in `discretisedfield`).

**Comment by fangohr** [comment]
Can you have a chat with Thomas about this? I have some ideas but he may know better :), or in any case we should know his view before making a decision.

**Comment by mb1a15** [comment]
After discussion with Thomas, we should let `matplotlib` to choose its default backend. Because of that, `matplolib.use("nbagg")` should be remove from `__init__.py`.

**Comment by mb1a15** [comment]
This is now changed on master.

matplotlib2 will be much smarter in choosing default backend. At the moment, we get a warning when we import matplotlib.

**Comment by mb1a15** [comment]
In order for tests to pass inside Docker (on TravisCI), we had to add

`ENV MPLBACKEND Agg`

to the Dockerfile.

**Comment by mb1a15** [comment]
Matplotlib now chooses default backend.

Waiting for matplotlib2...

**Comment by mb1a15** [comment]
Probably we need to make `discretisedfield` aware where it is run and make "Agg" default backend.

**Comment by mb1a15** [comment]
`"agg"` backend is now default.
