### ISSUE TITLE
OOMMF Installation Obstacles

### ISSUE THREAD

**Issue by mvousden** [joommf/joommf#35]
I could not install tclsh from the instructions in the repository. I had to create a tclsh symbolic link:
    `cd /usr/bin; sudo ln --symbolic tcl8.6 tclsh`

I also required the following environment variables, which were not documented:
    `OOMMF_TK_CONFIG=/usr/lib/x86_64-linux-gnu/tk8.6/tkConfig.sh`
    `OOMMF_TCL_CONFIG=/usr/lib/x86_64-linux-gnu/tk8.6/tclConfig.sh`
    `OOMMF_TK_INCLUDE_DIR=/usr/include/tk/`
    `OOMMF_TCL_INCLUDE_DIR=/usr/include/tcl/`

I am running Ubuntu 14.04, and installed tcl and tk from the tcl-dev and tk-dev packages in apt.

**Comment by mb1a15** [comment]
This should be a part of documentation.

**Comment by mb1a15** [comment]
Closely related to #34.

**Comment by mb1a15** [comment]
This was never encountered again.
