### ISSUE TITLE
Order columns in data table in 'useful' order

### ISSUE THREAD

**Issue by fangohr** [joommf/joommf#36]
Maybe have stages, steps, and time at the left, followed by mx, my, mz, and maybe Hx, Hy, Hz, and the max_spin angles. Then show the other columns in alphabetical order.

See for example table in https://github.com/joommf/oommfc/blob/master/docs/ipynb/standard_problem4.ipynb (at the moment in output cell [16]).

**Comment by mb1a15** [comment]
This is now issue number 1 in joommf/oommfodt. Therefore, this issue is now closed.
