### ISSUE TITLE
Offer function to check OOMMF-setup

### ISSUE THREAD

**Issue by fangohr** [joommf/joommf#38]
oommfc.oommf.check() -> do tests to confirm that OOMMF can be found. 
If we can call OOMMF (we may ask OOOMMF for its version number to check this), we could be silent.

If we cannot call OOMMF, we can print message with details:
- is OOMMTCL set? If so,  to where. Does the path exist?
- are we attempting to use docker? If so, can we talk to the docker machine?

We could have an extra switch to raise an exception if OOMMF cannot be found (useful for automatic tests).

**Comment by mb1a15** [comment]
This is now implemented as:

```
import oommfc
oommfc.oommf.status()
```

**Comment by mb1a15** [comment]
At the moment, `status` function requires three arguments, which is inconvenient for the user. Probably the simplest solution would be to organise `oommf` functions is a class.

Because of this, issue is reopened.

**Comment by mb1a15** [comment]
Now changed on master.
