### ISSUE TITLE
Saving other fields

### ISSUE THREAD

**Issue by ryanpepper** [joommf/joommf#44]
Currently, in the TimeDriver classes, the saving of the magnetisation is hard coded. We need to expose the option to save the other fields that OOMMF allows. For each energy class, we can also save the field and the energy density. The syntax for this (with Oxs_UniformExchange as the example) is:

```
Destination archive mmArchive
Schedule Oxs_UniformExchange::Field archive Step 1
Schedule "Oxs_UniformExchange::Energy density" archive Step 1
```

replace Step with Stage/Done as necessary. 

The inverted commas around the energy density part is needed because strings are first class citizens in Tcl, and the space gets misinterpreted otherwise.

**Comment by ryanpepper** [comment]
Other things that it's also possible to save are:
```
Oxs_CGEvolve::H
Oxs_CGEvolve::mxHxm
Oxs_CGEvolve::Total energy density
Oxs_MinDriver::Magnetization
Oxs_TimeDriver::Magnetization
Oxs_RungeKuttaEvolve::Total Field
Oxs_RungeKuttaEvolve::Total energy density
Oxs_RungeKuttaEvolve::dm/dt
Oxs_RungeKuttaEvolve::mxH
```
I've not checked the Euler evolver but I imagine it has the same options as the Runge Kutta one.

**Comment by mb1a15** [comment]
This issue is now mostly solved. The remaining fields are now part of #64
