### ISSUE TITLE
Author, email, and url in setup.py

### ISSUE THREAD

**Issue by mb1a15** [joommf/joommf#48]
At the moment, in all packages, we have:

```
url='https://github.com/joommf/joommfutil',
author='Computational Modelling Group',
author_email='fangohr@soton.ac.uk',
```

Should we maybe use `joommf.github.io` for url and `joommf-users` email?

**Comment by fangohr** [comment]
URL: yes
email: 'jupyteroommf@gmail.com'
author: 'Marijan Beg, Ryan Pepper and Hans Fangohr'

**Comment by mb1a15** [comment]
This is now changed in all repositories.
