### ISSUE TITLE
Allow the choice of where OOMMF is run

### ISSUE THREAD

**Issue by marijanbeg** [joommf/joommf#49]
At the moment if OOMMF is installed on the host machine, it is run on the host. If not, it is run inside Docker. User does not have any control of this process and cannot decide where to run OOMMF.

It would be useful, especially for testing, to specify via interface, where to run OOMMF. However, it is not clear how that should be specified. The most natural place would be in drivers or in its `drive` method. For instance,

```
td = oc.TimeDriver()
td.where = "host"  # or "docker"
td.drive(system, t=1e-9, n=100)
```

or

```
td = oc.TimeDriver()
td.drive(system, t=1e-9, n=100, where="host")
```

Also what would be the better name instead of `where`?

**Comment by fangohr** [comment]
I think we should have a configuration object. This should have a `name` attribute, and a `command` attribute. We should provide two default objects of this class, with attributes (approximately) like
```
docker.name = "docker"
docker.command = "docker run tclsh $OOMFTCL"
```
and
```
host.name = "host"
host.command = "tcsh $OOMMFTCL"
```

This allows the user to create more such configurations for their particular system.
We would then pass an instance of this configuration object `c` to the part of the code that needs to know it; so most directly the Driver. Within the driver, we can then just use the property `c.command` to execute the run.

We can provide the default config objects somewhere,  for example oommfc.oommf.docker and oommfc.oommf.host (you may know better where is good). We could - maybe after some testing - also provide the possibility to access these two via string names where we would normally pass the config class.

If required later, we can also add pre-execution command and post-execution commands to the configuration object etc.

If a user is not providing a configuration object, we should default to looking for OOMMF automatically: if OOMMF_TCL is defined on the host, let's try to run that OOMMF. If the variable is defined, but we can't call OOMMF (we can ask OOMMF for its version as a test), we should fail and report that the variable is set, but it doesn't work. If the variable is not set, we can try to connect to Docker, and run OOMMF there.

**Comment by marijanbeg** [comment]
This can now be done by instantiating a particular class derived from `OOMMFRunner`.
