### ISSUE TITLE
Add section to manual that helps users run a first example

### ISSUE THREAD

**Issue by fangohr** [joommf/joommf#56]
- tell user how to start the notebook
- provide getting started notebook that does something very simple, maybe like http://nmag.soton.ac.uk/nmag/current/manual/html/example1/doc.html, although a sphere is not a good choice for OOMMF. So maybe a cube that relaxes into a flower state, or a geometry that has shape anisotropy and the magnetisation, when relaxed, aligns with that. (We could plot he magnetisation before running the time driver, and afterwards?).

**Comment by mb1a15** [comment]
Notebook is now added to the documentation. Changes the direction of magnetisation, due to the Zeeman field, and takes into account the shape anisotropy (flower state).

The sample is a 100 nm edge cube.
