### ISSUE TITLE
Add links to the notebook based examples in OOMMC that allow download of the ipynb file

### ISSUE THREAD

**Issue by fangohr** [joommf/joommf#57]
This will make it a lot easier for users to explore the capabilities of the tool.

(In the long run, we may want to offer a zip file with all ipynb files, or something more convenient than having to download each file separately. We can do this later.)

**Comment by mb1a15** [comment]
At the moment, a link is added to the notebook from which it can be downloaded.

**Comment by mb1a15** [comment]
Unfortunately, the notebook must be downloaded with right click -> `save as...`

GitHub does not allow downloading individual files, only the entire repository (as as zip file). However, it allows accessing the raw content of individual files.
