### ISSUE TITLE
Website tweaks

### ISSUE THREAD

**Issue by ryanpepper** [joommf/joommf#58]
* Just noticed that the current website still points to oommffield rather than discretisedfield
* Template needs quite a bit of adjusting for the website to look sensible on mobile/tablet. Currently, logo disappears, text spans with huge separation when line wraps, (especially in FAQ).

Grammar:
* Get Started - "The best starting point are", "In addition to that," 
* Capitalisation - "python", etc.

**Comment by mb1a15** [comment]
The website has changed significantly since then, so changes suggested in this issue are outdated.

Website update is now #66
