### ISSUE TITLE
Allow installation of JOOMMF via anaconda

### ISSUE THREAD

**Issue by fangohr** [joommf/joommf#74]
We are making progress with this:

- conda rececies in http://github.com/joommf/conda-recipes
- some of these have been moved to conda-forge already
  - joommfutil, pyvtk, odttools, and oommf itself()
- the whole map of packages and dependencies is visible at https://github.com/joommf/conda-recipes/blob/master/dependencyplot.pdf

**Comment by fangohr** [comment]
## Documenting how to install JOOMMF with conda

When we write the documentation for this, one of the conda-forge maintainers suggests that we encourage users to write:

<pre>
conda config --add channels conda-forge
conda install oommf
</pre>

instead of 

<pre>
conda install -c conda-forge oommf
</pre>

he says: "I think since there are incompatibilities between defaults and conda-forge, you should recommend the above command. conda install -c conda-forge <pkg> might not work sometimes."

Source: https://github.com/conda-forge/staged-recipes/pull/3038#discussion_r119067420

**Comment by marijanbeg** [comment]
The package is now in conda-forge.
