### ISSUE TITLE
Tests in packages do not return 'exit code'

### ISSUE THREAD

**Issue by fangohr** [joommf/joommf#75]
Interesting observation: in this build for conda-forge (https://circleci.com/gh/conda-forge/staged-recipes/16795), the build process reports success, yet when browsing through the test results, we can see:
<pre>
 python -c 'import oommfc; oommfc.test()'
============================= test session starts ==============================
platform linux -- Python 3.6.1, pytest-3.1.2, py-1.4.34, pluggy-0.4.0 -- /staged-recipes/build_artefacts/oommfc_1497455444665/_t_env/bin/python
cachedir: .cache
rootdir: /staged-recipes/build_artefacts/oommfc_1497455444665/test_tmp, inifile:
collecting ... collected 126 items / 1 errors

==================================== ERRORS ====================================
______________________________ ERROR collecting  _______________________________
ImportError while importing test module '/staged-recipes/build_artefacts/oommfc_1497455444665/_t_env/lib/python3.6/site-packages/oommfc/tests/test_no_docker_running_raises_error.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../_t_env/lib/python3.6/site-packages/oommfc/tests/test_no_docker_running_raises_error.py:5: in <module>
    from testpath import modified_env
E   ModuleNotFoundError: No module named 'testpath'
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 1.01 seconds ============================
</pre>

I think the reason for this is that we call `pytest.main()` inside the Python program, and we don't return the exit code. Here is a prototype solution to address this:
The file `module.py` is
<pre>
import pytest

def test_mylibrary():
    """fake function test"""
    assert False

def test():
    return(pytest.main(["-v", "module.py"]))
</pre>

Import here is that the `test()` function returns the return value from `pytest.main`.

We need to change the way we call the tests in our condo-forge recipes. At the moment we have the following:
<pre>
bash-3.2$ python -c "import module; module.test()"
============================= test session starts ==============================
platform darwin -- Python 3.6.0, pytest-3.0.5, py-1.4.32, pluggy-0.4.0 -- /Users/fangohr/anaconda3/envs/joommf-dev/bin/python
cachedir: .cache
rootdir: /Users/fangohr/Desktop, inifile: 
plugins: cov-2.3.1
collected 2 items 

module.py::test_mylibrary FAILED
module.py::test PASSED

=================================== FAILURES ===================================
________________________________ test_mylibrary ________________________________

    def test_mylibrary():
        """fake function test"""
>       assert False
E       AssertionError

module.py:6: AssertionError
====================== 1 failed, 1 passed in 0.58 seconds ======================
</pre>
but we don't get the exit code at the shell:
<pre>
(joommf-dev) bash-3.2$ echo $?
0
</pre>
The following seems to do the job:
<pre>
bash-3.2$ python -c "import sys; import module; sys.exit(module.test())"
============================= test session starts ==============================
platform darwin -- Python 3.6.0, pytest-3.0.5, py-1.4.32, pluggy-0.4.0 -- /Users/fangohr/anaconda3/envs/joommf-dev/bin/python
cachedir: .cache
rootdir: /Users/fangohr/Desktop, inifile: 
plugins: cov-2.3.1
collected 2 items 

module.py::test_mylibrary FAILED
module.py::test PASSED

=================================== FAILURES ===================================
________________________________ test_mylibrary ________________________________

    def test_mylibrary():
        """fake function test"""
>       assert False
E       AssertionError

module.py:6: AssertionError
====================== 1 failed, 1 passed in 0.50 seconds ======================
(joommf-dev) bash-3.2$ echo $?
1
</pre>
Can we do any better? (@mb1a15, @takluyver?)

**Comment by fangohr** [comment]
Following a discussion with Marijan: we can use the line 
<pre>
python -c "import sys; import module; sys.exit(module.test())"
</pre>
already now (before our test function returns an integer). At the moment, we return `None` from the `test()` function, and this is passed to the shell as return value `0`:
<pre>
(joommf) iota:tmp fangohr$ cat module.py 
import pytest

def test_mylibrary():
    """fake function test"""
    assert False

def test():
    #return(pytest.main(["-v", "module.py"]))
    pytest.main(["-v", "module.py"])
    return None
(joommf) iota:tmp fangohr$ python -c "import sys; import module; sys.exit(module.test())"
============================= test session starts ==============================
platform darwin -- Python 3.6.0, pytest-3.1.1, py-1.4.34, pluggy-0.4.0 -- /Users/fangohr/anaconda/envs/joommf/bin/python
cachedir: .cache
rootdir: /Users/fangohr/tmp, inifile:
collected 2 items 

module.py::test_mylibrary FAILED
module.py::test PASSED

=================================== FAILURES ===================================
________________________________ test_mylibrary ________________________________

    def test_mylibrary():
        """fake function test"""
>       assert False
E       AssertionError

module.py:5: AssertionError
====================== 1 failed, 1 passed in 0.38 seconds ======================
(joommf) iota:tmp fangohr$ echo $?
0
</pre>

So we can go ahead with these changes in the `conda-forge/*-feedstock` repositories now already.

**Comment by takluyver** [comment]
The other option would be to invoke `py.test` directly to do the tests for conda rather than calling our `oommfc.test()` function.

**Comment by fangohr** [comment]
Yes, but I prefer to use the test function in the module as this is exactly how the users would use it. (Also: For running py.test, we need to find out where the files with the tests are etc.) 

Okay, we'll proceed with my suggestion above then; thank you.

**Comment by fangohr** [comment]
Done also for joommfutil -> 0.7.6 (on PyPI and condo-forge)

**Comment by fangohr** [comment]
Done for oommfodt -> 0.7.6 (https://github.com/joommf/oommfodt/pull/5)

**Comment by marijanbeg** [comment]
This is now fixed in all packages
