### ISSUE TITLE
Can JOOMMF perform the "Full three-dimensional simulation model"?

### ISSUE THREAD

**Issue by lamducduong184** [joommf/joommf#78]
Dear all,

I am using Joommf very well. Thanks the developer team so much!

Hamitonian for my system is like that:
system.hamiltonian = oc.Exchange(A=A) + oc.DMI(D=D, kind="interfacial") + oc.UniaxialAnisotropy(K1=K1, u=u) + oc.Demag()

Could you please tell me how to perform the "Full three-dimensional simulation model" in M. Beg et al Sci. Rep. 5, 17137 with Joommf?

Best regards,

**Comment by marijanbeg** [comment]
Hi, thank you for your question. We are happy to hear you find JOOMMF helpful. By a full three-dimensional model in that particular paper we mean that:

1. We have demagnetisation energy included. (as you already have in your Hamiltonian)
2. Our meshes are three dimensional. (in this case there is more than one layer of discretisation cells in the thickness direction). This is something I cannot see from your code, but if you send me the line of code where you create the mesh, we can discuss this further.

**Comment by marijanbeg** [comment]
Also, could you please raise any issues in the future at https://github.com/joommf/help/issues

This is the repository where users can post questions and ask for assistance.

**Comment by lamducduong184** [comment]
Thank you so much Marijan,
I have done it!
