### ISSUE TITLE
Mesh argument names

### ISSUE THREAD

**Issue by mb1a15** [joommf/joommf#9]
Arguments used to create a mesh should be renamed:

- `cmin` to `p1`
- `cmax` to `p2`
- `d` to `dxdydz` or `cell`

This issue is closely related to #2 and #12.

If eventually is decided that `fidimag` should use the finite difference `Mesh`, another arguments, such as `periodicity` should be added.

**Comment by mb1a15** [comment]
At the moment, they are renamed:

`cmin` -> `c1`
`cmax` -> `c2`
`d` -> `d`

"c" stands for coordinate. I think I prefer "p" as in point.

**Comment by fangohr** [comment]
+1

**Comment by mb1a15** [comment]
The argument names are now changed to `p1`, `p2`, and `cell`. Code still needs tidying up to make it consistent. All coordinates should be points.
