### ISSUE TITLE
Module (repository) name for data analysis

### ISSUE THREAD

**Issue by marijanbeg** [joommf/joommf#93]
What can be a good name for the data analysis module (repository)? This name should be available on PyPI and in Conda cloud. One suggestions would be `oommfdata`. Maybe `mumagdata` or `micromagneticdata` if we are going to make it more generic and not only for OOMMF. Also putting `tools` somewhere in the name can be an option.

Any thoughts?

**Comment by fangohr** [comment]
I agree that we should be looking beyond oommf, in particular as mumax produces very similar files (at least the omf/ovf files use the same format).

Some brainstorming/dump:

micromagneticdata
micromagneticdatatools
micromagneticdataanalysis
mumagtools
mumagdatascience
mumaganalysis

**Comment by marijanbeg** [comment]
Because we already have `micromagneticmodel` module, I would prefer not to use `mumag` in the name of the module. And out of three remaining options `micromagneticdata` is the shortest and somehow consistent with `micromagneticmodel`. This name is also available both on PyPI and in Conda Cloud. Therefore, I would proceed with `micromagneticdata`.

Discussed with @sergii-mamedov.
